import UserContext from 'src/contexts/UserContext'
import './globals.css'

export const metadata = {
  title: 'CuteBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Montserrat:wght@500;600;800&display=swap" rel="stylesheet"/>
      </head>
      <body>
        <UserContext>
          {children}
        </UserContext>
      </body>
    </html>
  )
}
